#!/bin/sh

set -e

GIT_DIR="${HOME}/git"
BOOTSTRAP_DIR="${GIT_DIR}/bootstrap"
BIN_DIR=${HOME}/bin

if [ "$0" == "bootstrap_setup" ]; then
	cd "${BOOTSTRAP_DIR}"
	zsh bootstrap2.sh
	exit
fi

if [ -d "${BOOTSTRAP_DIR}/.git" ]; then
  if [ "$1" != "NOUPDATE" ]; then
    echo Bootstrap repos exists. Updating...
    cd "${BOOTSTRAP_DIR}"
    if git pull | grep -w bootstrap; then
      echo Bootstrap might have been modified.
      echo Restarting...
      ${BOOTSTRAP_DIR}/bootstrap NOUPDATE
			exit
    fi
  fi
else
  echo No bootstrap repo, downloading from github...
  mkdir -p "${GIT_DIR}"
  cd "${GIT_DIR}"
  git clone git://github.com/e2/bootstrap.git
  cd "${BOOTSTRAP_DIR}"
  exit
fi

#setup bootstrap in ~/bin
mkdir -p ${BIN_DIR}
if [ ! -e ${BIN_DIR}/bootstrap ]; then
  ln -s ${BOOTSTRAP_DIR}/bootstrap ${BIN_DIR}/bootstrap
  ln -s ${BOOTSTRAP_DIR}/bootstrap ${BIN_DIR}/bootstrap_setup
  echo Ok, bootstrap installed in ${BIN_DIR}
  echo Now, run the following: ${BIN_DIR}/bootstrap_setup
  exit
else
  echo Run ${BIN_DIR}/bootstrap_setup
fi
